language: en
pipeline: supervised_embeddings

policies:
    - name: KerasPolicy
      batch_size: 512
      epochs: 300
      max_training_samples: 300
      max_history: 150
      featurizer:
          - name: MaxHistoryTrackerFeaturizer
            max_history: 150
            state_featurizer:
              - name: BinarySingleStateFeaturizer
    - name: MemoizationPolicy
      max_history: 150
    - name: FallbackPolicy
      nlu_threshold: 0.4
      core_threshold: 0.3
      fallback_action_name: action_default_fallback
    - name: FormPolicy
    - name: MappingPolicy
